name: CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

  deploy:
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo ""
