name: CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Build completed"

  deploy-development:
    needs: build
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Successfully deployed to development"

  deploy-production:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Successfully deployed to production"
